### ISSUE TITLE
Added Tutorial

### ISSUE THREAD

**Issue by JordanMakesMaps** [SMillerTime57/coralnet_api_deployer#2]
Hi Scott, 

Thanks  for creating this repo and the tutorial on CoralNet. I've taken your code and made it into a jupyter notebook to serve as a tutorial for anyone that might want to the use API in the future

You can find it [here](https://github.com/JordanMakesMaps/CoralNet-API)

Thanks again, cheers!

**Comment by S-D-Miller** [comment]
Hey Jordan,

This is really cool.  Thanks for putting it together!  Do you mind if I put a link to your tutorial in the README?

**Comment by JordanMakesMaps** [comment]
Not at all!
